//
//  loginInteractor.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 16/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func verifyLoginData(request: Login.verify.Request)
  func verifyLoginExistence()
}

protocol LoginDataStore
{
  var userData: UserData? { get }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  var userData: UserData?
  
  // MARK: Verify Login Data and fill userData if exist
  
  func verifyLoginData(request: Login.verify.Request)
  {
    worker = LoginWorker()
    worker?.fetchUserData(user: request.user, password: request.password) { data in
        var success: Bool = false
        
        if let userdata = data {
            self.userData = userdata
            self.worker?.saveLogin(userID: request.user, password: request.password)
            success = true
        } else {
            success = false
        }
        let response = Login.verify.Response(allowed: success)
        self.presenter?.presentUserDisplay(response: response)
    }
  }
    
    func verifyLoginExistence() {
        worker = LoginWorker()
        let login = worker?.loadLogin()
        presenter?.presentLogin(response: Login.savedLogin.Response(userID: login?.userID, password: login?.password))
    }
}
