//
//  loginInteractor.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 16/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func verifyLoginData(request: Login.Something.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  
  // MARK: Verify Login Data
  
  func verifyLoginData(request: Login.Something.Request)
  {
    worker = LoginWorker()
    worker?.verifyLoginData(user: request.user, password: request.password)
    
    let response = Login.Something.Response(allowed: false)
    presenter?.presentSomething(response: response)
  }
}
