//
//  loginWorker.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 16/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func fetchUserData(user: String, password: String, completionHandler: @escaping (UserData?) -> Void)
  {
        if LocalInputsValidation().isValidInputs(user: user, password: password) {
            
            DispatchQueue.main.async {
                BankAPINetwork().fetchUser(user: user, password: password) { (userData, userStoreError) in
                    if userStoreError == nil {
                        completionHandler(userData)
                    } else {
                        completionHandler (nil)
                    }
                }
            }
        } else {
            completionHandler (nil)
        }
  }
}
