//
//  loginPresenter.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 16/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    
  func presentUserDisplay(response: Login.verify.Response)
    func presentLogin(response: Login.savedLogin.Response)
}

class LoginPresenter: LoginPresentationLogic {
    
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
    func presentUserDisplay(response: Login.verify.Response) {
        let viewModel = Login.verify.ViewModel(allowed: response.allowed)
        viewController?.displayLogin(viewModel: viewModel)
    }
    
    func presentLogin(response: Login.savedLogin.Response) {
        let viewModel = Login.savedLogin.ViewModel(userID: response.userID, password: response.password)
        viewController?.displaySavedLogin(viewModel: viewModel)
    }
}
