//
//  loginInteractor.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 16/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol loginBusinessLogic
{
  func verifyLoginData(request: login.Something.Request)
}

protocol loginDataStore
{
  //var name: String { get set }
}

class loginInteractor: loginBusinessLogic, loginDataStore
{
  var presenter: loginPresentationLogic?
  var worker: loginWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func verifyLoginData(request: login.Something.Request)
  {
    worker = loginWorker()
    worker?.doSomeWork()
    
    let response = login.Something.Response(allowed: false)
    presenter?.presentSomething(response: response)
  }
}
