////
////  UserProfilePresenterTests.swift
////  BrunoCcySantander
////
////  Created by Bruno Chen on 17/06/20.
////  Copyright (c) 2020 Bruno Chen. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import BrunoCcySantander
//import XCTest
//
//class UserProfilePresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: UserProfilePresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupUserProfilePresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupUserProfilePresenter()
//  {
//    sut = UserProfilePresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class UserProfileDisplayLogicSpy: UserProfileDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: UserProfile.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = UserProfileDisplayLogicSpy()
//    sut.viewController = spy
//    let response = UserProfile.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
