//
//  UserProfileWorkerTests.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BrunoCcySantander
import XCTest

class UserProfileWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: UserProfileWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupUserProfileWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupUserProfileWorker()
  {
    sut = UserProfileWorker()
  }
  
  // MARK: Test doubles
  class BankAPISpy: BankAPINetworkProtocol
  {
    var iscalled: Bool = false
    
      var userData = UserData(userAccount: UserAccount(userID: 10, name: "name", bankAccount: "bankAccount", agency: "agency", balance: 1.0), error: ErrorUserAPI())
      
      func fetchUser(user: String, password: String, completionHandler: @escaping (UserData?, UserStoreError?) -> Void) {
          completionHandler(userData, nil)
      }
      
      
      var statementListData = StatementListData(statementList: [StatementList(title: "title", desc: "desc", date: "date", value: 1.0)], error: ErrorAPI())
      
      func fetchStatementList(userID: String, completionHandler: @escaping (StatementListData?, UserStoreError?) -> Void) {
            iscalled = true
          completionHandler(statementListData, nil)
      }
  }
  // MARK: Tests
  
  func testFetchStatementList()
  {
    // Given
    let apiSpy = BankAPISpy()
    sut.bankAPINetwork = apiSpy

    // When
    sut.fetchStatementList(completionHandler: { (statementArray) in
        XCTAssertFalse(apiSpy.iscalled, "testFetchUserData(request:) should ask the presenter to format the result")
    })
  }
}
