////
////  UserProfileInteractorTests.swift
////  BrunoCcySantander
////
////  Created by Bruno Chen on 17/06/20.
////  Copyright (c) 2020 Bruno Chen. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import BrunoCcySantander
//import XCTest
//
//class UserProfileInteractorTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: UserProfileInteractor!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupUserProfileInteractor()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupUserProfileInteractor()
//  {
//    sut = UserProfileInteractor()
//  }
//  
//  // MARK: Test doubles
//  
//  class UserProfilePresentationLogicSpy: UserProfilePresentationLogic
//  {
//    var presentSomethingCalled = false
//    
//    func presentSomething(response: UserProfile.Something.Response)
//    {
//      presentSomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testDoSomething()
//  {
//    // Given
//    let spy = UserProfilePresentationLogicSpy()
//    sut.presenter = spy
//    let request = UserProfile.Something.Request()
//    
//    // When
//    sut.doSomething(request: request)
//    
//    // Then
//    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
//  }
//}
