////
////  UserProfileWorkerTests.swift
////  BrunoCcySantander
////
////  Created by Bruno Chen on 17/06/20.
////  Copyright (c) 2020 Bruno Chen. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import BrunoCcySantander
//import XCTest
//
//class UserProfileWorkerTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: UserProfileWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupUserProfileWorker()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupUserProfileWorker()
//  {
//    sut = UserProfileWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething()
//  {
//    // Given
//    
//    // When
//    
//    // Then
//  }
//}
