//
//  UserProfilePresenterTests.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BrunoCcySantander
import XCTest

class UserProfilePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: UserProfilePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupUserProfilePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupUserProfilePresenter()
  {
    sut = UserProfilePresenter()
  }
  
  // MARK: Test doubles
  
  class UserProfileDisplayLogicSpy: UserProfileDisplayLogic
  {
    
    var displaySomethingCalled = false
    
    func displayUserInfo(viewModel: UserProfile.UserInfo.ViewModel) {
        displaySomethingCalled = true
    }
    
    func displayStatementListInfo(viewModel: UserProfile.StatementListInfo.ViewModel) {
        displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentStatementList()
  {
    // Given
    let spy = UserProfileDisplayLogicSpy()
    sut.viewController = spy
    let response = UserProfile.StatementListInfo.Response(statementList: [StatementList(title: "title", desc: "desc", date: "date", value: 1.0)])
    
    // When
    sut.presentStatementList(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentStatementList(response:) should ask the view controller to display the result")
  }
}
