//
//  userInteractor.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 16/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol userBusinessLogic
{
  func doSomething(request: user.Something.Request)
}

protocol userDataStore
{
  //var name: String { get set }
}

class userInteractor: userBusinessLogic, userDataStore
{
  var presenter: userPresentationLogic?
  var worker: userWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: user.Something.Request)
  {
    worker = userWorker()
    worker?.doSomeWork()
    
    let response = user.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
