//
//  UserProfilePresenter.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfilePresentationLogic
{
  func presentSomething(response: UserProfile.Something.Response)
}

class UserProfilePresenter: UserProfilePresentationLogic
{
  weak var viewController: UserProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UserProfile.Something.Response)
  {
    let viewModel = UserProfile.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
