//
//  UserProfileViewController.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfileDisplayLogic: class
{
  func displayUserInfo(viewModel: UserProfile.UserInfo.ViewModel)
  func displayStatementListInfo(viewModel: UserProfile.StatementListInfo.ViewModel)
}

class UserProfileViewController: UITableViewController, UserProfileDisplayLogic
{
  var interactor: UserProfileBusinessLogic?
  var router: (NSObjectProtocol & UserProfileRoutingLogic & UserProfileDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = UserProfileInteractor()
    let presenter = UserProfilePresenter()
    let router = UserProfileRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    loadUserInfo()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var lbName: UILabel!
    @IBOutlet weak var lbAccount: UILabel!
    @IBOutlet weak var lbBalance: UILabel!
    
   
  @IBAction func logout(_ sender: UIButton) {
    interactor?.logoutUser()
    navigationController?.popToRootViewController(animated: true)
  }
    
  func loadUserInfo()
  {
    let request = UserProfile.UserInfo.Request()
    interactor?.getUserInfo(request: request)
  }
  
  func displayUserInfo(viewModel: UserProfile.UserInfo.ViewModel)
  {
    lbName.text = viewModel.name
    lbAccount.text = viewModel.bankAgencyAccount
    lbBalance.text = viewModel.balance
  }
    
  func loadStatementInfo()
  {
    let request = UserProfile.StatementListInfo.Request()
    interactor?.getStatementListInfo(request: request)
  }
  
  func displayStatementListInfo(viewModel: UserProfile.StatementListInfo.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
}
