//
//  UserProfileViewController.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfileDisplayLogic: class
{
  func displayUserInfo(viewModel: UserProfile.UserInfo.ViewModel)
  func displayStatementListInfo(viewModel: UserProfile.StatementListInfo.ViewModel)
}

class UserProfileViewController: UITableViewController, UserProfileDisplayLogic
{
  var interactor: UserProfileBusinessLogic?
  var router: (NSObjectProtocol & UserProfileRoutingLogic & UserProfileDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = UserProfileInteractor()
    let presenter = UserProfilePresenter()
    let router = UserProfileRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    loadUserInfo()
    registerTableViewCells()
    fetchStatementInfo()
  }
    
  // MARK: Table view
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedStatements.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        return configureItemCell(forRowAt: indexPath)
        
    }
    
    private func registerTableViewCells()
    {
      let statementCellNib = UINib(nibName: "StatementListCell", bundle: nil)
      tableView.register(statementCellNib, forCellReuseIdentifier: "StatementListCell")
    }
    
    private func configureItemCell(forRowAt indexPath: IndexPath) -> StatementTableViewCell
    {
      let cell = tableView.dequeueReusableCell(withIdentifier: "StatementListCell", for: indexPath) as! StatementTableViewCell
      cell.statement = displayedStatements[indexPath.row]
      return cell
    }
    
  
  // MARK: Fetch objects
  
    @IBOutlet weak var lbName: UILabel!
    @IBOutlet weak var lbAccount: UILabel!
    @IBOutlet weak var lbBalance: UILabel!
    
   
  @IBAction func logout(_ sender: UIButton) {
    interactor?.logoutUser()
    navigationController?.popToRootViewController(animated: true)
  }
    
  var displayedStatements = [UserProfile.StatementListInfo.ViewModel.DisplayedStatement]()
  var displayedUserProfile: UserProfile.UserInfo.Request!
    
  func loadUserInfo()
  {
    interactor?.getUserInfo()
  }
  
  func displayUserInfo(viewModel: UserProfile.UserInfo.ViewModel)
  {
    lbName.text = viewModel.name
    lbAccount.text = viewModel.bankAgencyAccount
    lbBalance.text = viewModel.balance
  }
    
  func fetchStatementInfo()
  {
    let request = UserProfile.StatementListInfo.Request()
    interactor?.getStatementListInfo(request: request)
  }
  
  func displayStatementListInfo(viewModel: UserProfile.StatementListInfo.ViewModel)
  {
    displayedStatements = viewModel.displayedStatement
    tableView.reloadData()
  }
    
}
