//
//  UserProfileInteractor.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfileBusinessLogic
{
  func getUserInfo(request: UserProfile.UserInfo.Request)
  func getStatementListInfo(request: UserProfile.StatementListInfo.Request)
  func logoutUser()
}

protocol UserProfileDataStore
{
  var userData: UserData? { get set }
}

class UserProfileInteractor: UserProfileBusinessLogic, UserProfileDataStore
{
  var presenter: UserProfilePresentationLogic?
  var worker: UserProfileWorker?
  var userData: UserData?
  
  // MARK: Do something
  
  func getUserInfo(request: UserProfile.UserInfo.Request)
  {
    worker = UserProfileWorker()
    worker?.doSomeWork()
    
    let response = UserProfile.UserInfo.Response(userData: userData!)
    presenter?.presentUserInfo(response: response)
  }
    
  func getStatementListInfo(request: UserProfile.StatementListInfo.Request)
  {
//    worker = UserProfileWorker()
//    worker?.doSomeWork()
//    
//    let response = UserProfile.UserInfo.Response(userData: UserData(userAccount: UserAccount(userID: 10, name: "", bankAccount: "", agency: "", balance: 1.0), error: ErrorUserAPI()))
//    presenter?.presentSomething(response: response)
  }
    
    func logoutUser() {
        
    }
    
}
