//
//  UserProfileWorker.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UserProfileWorker
{
  func fetchStatementList(completionHandler: @escaping ([StatementList]) -> Void)
  {
    let loginData = UserKeychainService().getUserPassword()
    DispatchQueue.main.async {
        BankAPINetwork().fetchStatementList(userID: loginData.userID ?? "") { (statementListData, userStoreError) in
            let statementList: [StatementList] = statementListData!.statementList
            completionHandler(statementList)
        }
    }
  }
}
