//
//  UserProfileRouter.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserProfileRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UserProfileDataPassing
{
  var dataStore: UserProfileDataStore? { get }
}

class UserProfileRouter: NSObject, UserProfileRoutingLogic, UserProfileDataPassing
{
  weak var viewController: UserProfileViewController?
  var dataStore: UserProfileDataStore?
  
}
