//
//  LoginPresenterTests.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BrunoCcySantander
import XCTest

class LoginPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LoginPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupLoginPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLoginPresenter()
  {
    sut = LoginPresenter()
  }
  
  // MARK: Test doubles
  
  class LoginDisplayLogicSpy: LoginDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displayLogin(viewModel: Login.verify.ViewModel) {
        displaySomethingCalled = true
    }
    
    func displaySavedLogin(viewModel: Login.savedLogin.ViewModel) {
        displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentUserDisplay()
  {
    // Given
    let spy = LoginDisplayLogicSpy()
    sut.viewController = spy
    let response = Login.verify.Response(allowed: true)
    
    // When
    sut.presentUserDisplay(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentUserDisplay(response:) should ask the view controller to display the result")
  }
}
