//
//  LoginInteractorTests.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BrunoCcySantander
import XCTest

class LoginInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LoginInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupLoginInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLoginInteractor()
  {
    sut = LoginInteractor()
  }
  
  // MARK: Test doubles
  
  class LoginPresentationLogicSpy: LoginPresentationLogic
  {
    
    var presentSomethingCalled = false
    
    func presentUserDisplay(response: Login.verify.Response) {
        presentSomethingCalled = true
    }
    
    func presentLogin(response: Login.savedLogin.Response) {
        presentSomethingCalled = true
    }
    
  }
  
  // MARK: Tests
  
  func testVerifyLoginData()
  {
    // Given
    let spy = LoginPresentationLogicSpy()
    sut.presenter = spy
    let request = Login.verify.Request(user: "", password: "")
    
    // When
    sut.verifyLoginData(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
