//
//  LoginViewControllerTests.swift
//  BrunoCcySantander
//
//  Created by Bruno Chen on 17/06/20.
//  Copyright (c) 2020 Bruno Chen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BrunoCcySantander
import XCTest

class LoginViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LoginViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupLoginViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLoginViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
    sut = (storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController)
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class LoginBusinessLogicSpy: LoginBusinessLogic
  {

    
    var doSomethingCalled = false
    
    func verifyLoginData(request: Login.verify.Request) {
        doSomethingCalled = true
    }
    
    func verifyLoginExistence() {
        doSomethingCalled = true
    }
    
  }
  
  // MARK: Tests
  
  func testShouldDoSomethingWhenViewIsLoaded()
  {
    // Given
    let spy = LoginBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
  }
  
  func testDisplaySomething()
  {
    // Given
    let viewModel = Login.savedLogin.ViewModel(userID: "user", password: "123")
    
    // When
    loadView()
    sut.displaySavedLogin(viewModel: viewModel)
    
    // Then
    XCTAssertEqual(sut.tfUser.text, "user", "displaySavedLogin(viewModel:) should update the user text field")
    XCTAssertEqual(sut.tfPassword.text, "123", "displaySavedLogin(viewModel:) should update the password text field")
  }
}
